### ISSUE TITLE
Broken after update

### ISSUE THREAD

**Issue by Mrpuppyz** [meeb/tubesync#309]
I pulled the new image that was just released today using portainer. After the container was restarted I was not able to get the page to load and now there are errors in my logs. 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: fatal: timed out

Did I maybe do something wrong?

**Comment by Mrpuppyz** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: fatal: timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service tubesync-init: command exited 111
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
  Applying sync.0013_fix_elative_media_file...3s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
  Applying sync.0013_fix_elative_media_file...3s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out



As far as I can tell it's having issues when it's t running migration

**Comment by Mrpuppyz** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: fatal: timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service tubesync-init: command exited 111
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
  Applying sync.0013_fix_elative_media_file...3s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
  Applying sync.0013_fix_elative_media_file...3s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out



As far as I can tell it's having issues when it's t running migration

**Comment by meeb** [comment]
Yeah this was just the default timeout with the new init version. This should already be fixed in ':latest' see if it have an image update you can pull.

**Comment by Mrpuppyz** [comment]
These logs are from the new image. I just now deleted the image and redownloaded it and I'm still having the problem. Here are the logs that I just now got from the redownload latest version


s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service tubesync-init: command exited 111

**Comment by UniverseXXX** [comment]
Got the same error.

**Comment by meeb** [comment]
OK, try pulling `:latest` again, yet more timeouts have been increased. You don't need to spam any more logs. Also you can temporarily fix this by using something like:

```bash
$ docker exec -ti tubesync /command/s6-setuidgid app /usr/bin/python3 /app/manage.py migrate
$ docker restart tubesync
```

**Comment by Mrpuppyz** [comment]
Running the migrate command did fix the issue for me. Took about 5 minutes for the command to complete. Probably because I have 60 sources added. It was hitting my sata ssd with full read and write speeds. Sorry I posted to many logs. I was trying to make sure I didn't leave anything important out.

**Comment by meeb** [comment]
Thanks for the feedback. I'll increase the timeout even further in future then as it's currently at 60 seconds.
